name: pleasepleasepleaseplease
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  async: ^2.11.0
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.4
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_slidable: ^3.0.0
  get_time_ago: ^1.2.4
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  image_picker_for_web: ^3.0.0
  modal_bottom_sheet: ^3.0.0-pre
  path: ^1.8.3
  peanut: ^5.0.0
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
